const RAW_NOMBA_CERTIFICATE_ELIGIBLE_EMAILS = `
systyn-labs@proton.me
johnpaulchigozie7@gmail.com
kingdavidinhim@gmail.com
idemekan20@gmail.com
etoo3604@gmail.com
ogunodemarvellous@gmail.com
nmanagi23@gmail.com
ntmark2004@gmail.com
esuekanem0@gmail.com
adeyemipaul2003@gmail.com
mabdurrahman.balogun@gmail.com
danielchukwuemela751@gmail.com
gagbedejobi@gmail.com
moloruntomiwa31@gmail.com
ayanboyewinner@gmail.com
kingsleychibueze16@gmail.com
righteousnessude@gmail.com
125chotumorgan@gmail.com
fortitudeodunlami@gmail.com
starduke001@gmail.com
olagbemisoyee@gmail.com
mondayimeobong@gmail.com
muskafahmad2@gmail.com
abdulhakeemakinola@gmail.com
davidokocha086@gmail.com
kolomodenikpi@gmail.com
eakerele71@gmail.com
Chiefezeko@gmail.com
motrenewed@gmail.com
oyewalemarvellous0@gmail.com
alumonabenaiah71@gmail.com
adetunjiadeyinka29@gmail.com
adeyemitaiwo24434@gmail.com
ayindesamuel0@gmail.com
ezekielbalogun56@gmail.com
ikorosamuel1@gmail.com
adzapesolomon@gmail.com
hemmyhteccreatives@gmail.com
stillkhaleefah@gmail.com
Ogiethompson11@gmail.com
amaechichibueze85@gmail.com
oyebowaleabdulmuiz@gmail.com
nkemaconam@gmail.com
adabisihannah363@gmail.com
ekongjemimah@gmail.com
josephisrael206@gmail.com
alliekundayo6@gmail.com
1harrydev@gmail.com
okparajamesuchechi@gmail.com
mayowaayeni69@gmail.com
oladipoelijah77@gmail.com
vicfegha@gmail.com
mokwechibuike7@gmail.com
uvietoboretreasure@gmail.com
appdever01@gmail.com
enochid200@gmail.com
onasanyadaniel794@gmail.com
akintunden18@gmail.com
akinloludamilolajanet@gmail.com
oyedelemartins65@gmail.com
jeremiahalbert003@gmail.com
idowu.tobi.saas.dev@gmail.com
adejorion@gmail.com
Victorhezishere@gmail.com
yusufolasunkanmi651@gmail.com
gideonabe2020@gmail.com
agbajep01@gmail.com
oreoluwaisrael07@gmail.com
jejeniyi7@gmail.com
sandraolajumoke58@gmail.com
silasadinoyi@gmail.com
oluwafemiajayiopemipo1@gmail.com
opeyemi.c.babarinde@gmail.com
bellobambo21@gmail.com
bellobambo21@gmail.com
isrealopa@gmail.com
hazeezet@gmail.com
omotomoniyi@gmail.com
eniolamiseyi62@gmail.com
adrienoke@gmail.com
olamidekolawole33@gmail.com
kingusang09@gmail.com
ikennaexcel21@gmail.com
omajeneoghenefega11@gmail.com
tobbytobs1@gmail.com
tobbytobs1@gmail.com
davidifebueme@gmail.com
Godstimeedokpayi@gmail.com
Akhabapatrick@gmail.com
omene.mudiaga@gmail.com
olusameze@gmail.com
alabiemmanuelferanmi@gmail.com
degenmeowster@gmail.com
adeyemoadebayo603@gmail.com
oderinwalesamson1@gmail.com
vohachor@gmail.com
adebayopetergvmc68@gmail.com
ollyphel@gmail.com
elusive4dev@gmail.com
oluwadare458@gmail.com
jameskefaslungu@gmail.com
oviedavid77@gmail.com
adekeyeimmanuel@gmail.com
alabims10@gmail.com
chinochinedu@gmail.com
jibrilmjibril05@gmai.com
julianlouis590@gmail.com
judenwadinobi.3@gmail.com
davidnobody0108@gmail.com
webmastersmma@gmail.com
umarpharouq456@gmail.com
oretanthompson@gmail.com
tominiyirheobot@gmail.com
eyoemmanuel180@gmail.com
petermmuo05@gmail.com
odushileomodolapo1995@gmail.com
emmanuelgiftee@gmail.com
peterolowooje360@gmail.com
leoemaxie@gmail.com
leoemaxie@gmail.com
adetolafatiha@gmail.com
abdullahioye10@gmail.com
tobechukwuegboh@gmail.com
apatirasulayman@gmail.com
qlasisi15@gmail.com
adamlaw669@gmail.com
coder0214h@gmail.com
sannishazily@gmail.com
ubadinekeprince@gmail.com
immadominion@gmail.com
sampson.gbewa32@gmail.com
taofeeqomotolani@gmail.com
chibuezenwajiobi@gmail.com
onyekachimaximillian@gmail.com
dimejirsq@yahoo.com
dimejirsq@yahoo.com
boboffiong99@gmail.com
abbeystack@gmail.com
andypraise890@gmail.com
chukwukelvin141@gmail.com
chukwukelvin141@gmail.com
Rcabiodun@gmail.com
umehemmanuel22@gmail.com
jeremiahalbert003@gmail.com
abubakarbabatunde20@gmail.com
rajiabdullahi907@outlook.com
anateboy01@gmail.com
lukmanuthman135@gmail.com
raphaelfaboyinde27@gmail.com
abdulmuhminsodiqadekunle@gmail.com
ukanah15thdean@gmail.com
atembarry12@gmail.com
sinmi2404@gmail.com
olamilekankareem717@gmail.com
manassehoruebor@gmail.com
ezeadannalyn@gmail.com
osazuwamatthewogbebor@gmail.com
daniel@taxcalc.ng
glo.obiorah@gmail.com
ehiomhentreasureruth@gmail.com
emmanuelajike2000@gmail.com
ogundipekhalid265@gmail.com
chuksy3@gmail.com
estherappolos51@gmail.com
captainvee3@gmail.com
olasunkanmiakeem816@gmail.com
princeghardemuyiwa@gmail.com
okechukwuchidera12@gmail.com
johnpenuel03@gmail.com
fiyinodusola@gmail.com
Oloweoluwadarasimi@gmail.com
izeaishat@gmail.com
ifeoluwa.designs@gmail.com
adamadekanye941@gmail.com
ayomideyolasunkanmi25@gmail.com
cozjahboi@gmail.com
jofesdavid@gmail.com
kanyinsola.fagbayi@gmail.com
caritaemelie@gmail.com
danielolamilekan749@gmail.com
Ajanlekokomotun@gmail.com
azeezakinkunmi02@gmail.com
adejaredaniel12@gmail.com
inuoluwadunsimi1@gmail.com
judeoscar2002@gmail.com
hesedanu@gmail.com
ismailajingi737@gmail.com
adaobilynda1234@gmail.com
okwuosahpaschal@gmail.com
sadiqadetola08@gmail.com
yasiroyebo@gmail.com
ladiposamuel30@gmail.com
baloguntoluwalope76@gmail.com
amoomustakim@gmail.com
Muhammednazir200717@gmail.com
pascal.amah10@gmail.com
caesarokeke57@gmail.com
mondayitohowo3@gmail.com
progressphilemon@gmail.com
achasaviourikhamate@gmail.com
absylver@gmail.com
umohchristian001@gmail.com
ejoel0035@gmail.com
maryjanechukelu@gmail.com
chukwuemekaazu97@gmail.com
emmanuelapabiekun@gmail.com
enyiokohilda@gmail.com
adindukingson@gmail.com
tochukwunwosa28@gmail.com
busayosalisu@gmail.com
dadavictory2000@gmail.com
nuhflexdreams20@gmail.com
olanniel04@gmail.com
chinedu.mbah.g20@gmail.com
bjorndonaldb@gmail.com
danielokoronkwo90@gmail.com
onwuagbasomto@gmail.com
lanrethesage@gmail.com
ukemeetim2222@gmail.com
davidezeike6@gmail.com
techviews.eghos@gmail.com
ehimex2005@gmail.com
wiszy522@gmail.com
animarvelous010@gmail.com
franklinuchendu5@gmail.com
Okekeekene367@gmail.com
philipprecious157@gmail.com
joshuaalabi2008@gmail.com
preciousigbayisemore001@gmail.com
adefolarinhackaton01@gmail.com
habeebroy96@gmail.com
ogheneroclark33@gmail.com
johnamos896@gmail.com
wittyambivert@gmail.com
gozione3@gmail.com
fortuneokpara7@gmail.com
daviduche176@gmail.com
daviduche176@gmail.com
victorodivine@gmail.com
aulex500@gmail.com
aulex500@gmail.com
kasalidamilola123@gmail.com
johnolufemiking@gmail.com
chukjosh07@gmail.com
omoyelekhalid11@gmail.com
davidukah7@gmail.com
ememzyvisuals@gmail.com
olayinkaemma27@gmail.com
ajokeashiah7@gmail.com
ayomiderasq6@gmail.com
danielsolomongs888@gmail.com
bakarezainab47@gmail.com
donslice6@gmail.com
ayodeletemitopelydia@gmail.com
sammyadetoye@gmail.com
olaosebikanbidemi@gmail.com
mustapha.ddare@gmail.com
Ademola@amala.cloud
Lucky@amala.cloud
oluwatimilehin@amala.cloud
Fatihat@amala.cloud
Lois@amala.cloud
abdulmuiz@amala.cloud
tobiemma200@gmail.com
olugbojiobafemi@gmail.com
adoledavid345@gmail.com
enweremproper@gmail.com
olaoluwaoyetibo@gmail.com
hermeschigoziri@gmail.com
ademoladeremi0@gmail.com
jp0712002@gmail.com
ezekielolaniyi323@gmail.com
richesmetelewawon@gmail.com
myspheet@gmail.com
Peazzycole@gmail.com
amamahjoy@gmail.com
akanniemmanuel33@gmail.com
avodeyon.7@gmail.com
agulonyemicheal9@gmail.com
babaniyiakinjiola@gmail.com
soliukabiru07@gmail.com
olaiwonismail@gmail.com
akapsyjr@gmail.com
mayortitilola39@gmail.com
2021.cee.jay@gmail.com
Raheematakeem@gmail.com
adisamuiz2603@gmail.com
claverejibe3@gmail.com
oyetadeoluwafemi2005@gmail.com
abdulsalamlawal011@gmail.com
adetunjiabdullahi2406@gmail.com
kingsmichael.official@gmail.com
josephlamidijoslam@gmail.com
omijiemichael435@gmail.com
odulanaprogress@gmail.com
odulanaprogress@gmail.com
izuobagoodness8@gmail.com
davidoyewole300@gmail.com
emmanueloyewole300@gmail.com
odebzemmygee@gmail.com
danielaborowa001@gmail.com
emaluwaseun@gmail.com
danielaborowa001@gmail.com
farouqokeniyi2004@gmail.com
iyinpelumi@gmail.com
eeman1adeniran@gmail.com
judahadetunji@gmail.com
gospelifeadi12@gmail.com
eyitayobembe@gmail.com
semiloreomotade@gmail.com
noahfola2005@gmail.com
chiamakamaduike@gmail.com
officialolamide001@gmail.com
femiblessing02@gmail.com
atohorokeno@gmail.com
jangjason27@gmail.com
mail.ceetrine@gmail.com
adeyeyeomokorede@gmail.com
onitimotee@gmail.com
bolodeokuolubodun@gmail.com
emmanuelatujuniorntun@gmail.com
princefrank269@gmail.com
iromjai111@gmail.com
megamindtheincredible@gmail.com
teniolatimothy@gmail.com
eniolabadmus351@gmail.com
davidkenechukwu591@gmail.com
davidmgbede75@gmail.com
davidmgbede75@gmail.com
favormandy@gmail.com
angsonola@gmail.com
angsonola@gmail.com
afolabiifeoluwa06@gmail.com
oyedejisamuel05@gmail.com
mahmud.adegboyega@gmail.com
nwadiaromiraclechukwuma@gmail.com
drimesbot@gmail.com
judgepaulogebe@gmail.com
oluwatobimercy032@gmail.com
tijaniabdulafeez05@gmail.com
ajibosoadeola@gmail.com
bajomosemilore@gmail.com
okaforbernadette3@gmail.com
solex247@gmail.com
coolerputt@gmail.com
olarenwajuabass825@gmail.com
Olalererobiu67@gmail.com
Ibraheemsalam06@gmail.com
emavec2002@gmail.com
amooademola55@gmail.com
vitalis.ngam24@gmail.com
adebayorvictor1997@gmail.com
joelbright508@gmail.com
preciouskayili@gmail.com
olapademicheal3@gmail.com
felixmedia78@gmail.com
T.babalolajoseph@gmail.com
praisechinonso21@gmail.com
apataomotayo0@gmail.com
naajihibnsiraj@gmail.com
chiboyekene1@gmail.com
abdullahioriola02@gmail.com
benjaminnkemfrancis@gmail.com
ayowolesodipe@gmail.com
quadrishola03@gmail.com
favourdomirin@gmail.com
faveejiofor2009@gmail.com
samuelobimbaawesome@gmail.com
Preciousuwadone@gmail.com
owendigitals@gmail.com
abdulwasiuubaydah@gmail.com
zainabfadeyi@gmail.com
stanleydiki@gmail.com
ceze5265@gmail.com
abasiofon135@gmail.com
idighekereudo@gmail.com
covenantmonday830@gmail.com
umichaeledet003@gmail.com
alhemdrewdavenchi001@gmail.com
obasootosegun@gmail.com
greg.ethel@gmail.com
pelumipeterz2014@gmail.com
kevingeorgewill@gmail.con
bolaji.m.luqman@gmail.com
bolaji.m.luqman@gmail.com
adeniyirahmat5@gmail.com
dasuccessblogger@gmail.com
damilolaoni15@gmail.com
adetulatestimony@gmail.com
icsidavid@gmail.com
okeakputochukwu9@gmail.com
sammyboy.as@gmail.com
adedejiadebayo732@gmail.com
mokhefue@gmail.com
fifsabol@gmail.com
gogunkanmbi@gmail.com
eabdulbaasit@gmail.com
ighodaropriscilia@gmail.com
Saliuoazeez@gmail.com
theophilusp2014@gmail.com
chrisumechukwu@gmail.com
olugbasaahmed@gmail.com
akudechidera@gmail.com
olalekanabidemi905@gmail.com
oluwatosinodejide121@gmail.com
ogunleyepelumi123@gmail.com
khingkehad01@gmail.com
catherineojong002@gmail.com
soyombotomiwa@gmail.com
omogboluwaga2013@gmail.com
muhammadzenqeeth@gmail.com
marceljekwu@gmail.com
akandesamad26@gmail.com
ayekudemilade43@gmail.com
eogerald.07@gmail.com
tobilobamusic@gmail.com
faithinator.faithanic@gmail.com
ajimatioseoluwa5@gmail.com
henryautomobiles75@gmail.com
erurehdarrel@gmail.com
sakawahab03@gmail.com
oyewaleadedunmola@gmail.com
afolabisamson20@gmail.com
ayanfedorcas2017@gmail.com
michaelgbenga91@gmail.com
salaudeenmubarakstar@gmail.com
wisdomleonard167@gmail.com
fakorodeayomide31@gmail.com
sheidabdulahad0@gmail.com
mmesomaonuegbu9@gmail.com
abiolaanjie@gmail.com
gospelmairo@gmail.com
amanabridget03@gmail.com
abdulrahmon11052008@gmail.com
kolawolebilaal13@gmail.com
sherifdeenraji96@gmail.com
boomweb3writes@gmail.com
muhibatbankole2@gmail.com
favouraugustine911@gmail.com
bamgbosechristian@gmail.com
okikday@gmail.com
Sanisherif838@gmail.com
awesomeakokayo@gmail.com
ogennaisrael98@gmail.com
ugohhenry71@gmail.com
Matthewakinloye95@gmail.com
promiseoluseyi@gmail.com
olalekanibrahim011@gmail.com
somininye@gmail
somininye@gmail.com
obison360@gmail.com
Shittumalik91@gmail.com
elemifesinachisimon@gmail.com
onadiranght2019@gmail.com
feranmijogbodo@gmail.com
nuloafrica@gmail.com
terver.orbunde@gmail.com
kellyowoju@gmail.com
yakubhassan057@gmail.com
righteousnessakinbola@gmail.com
ogoayorindeshekinah@gmail.com
yahyasaid935@gmail.com
jaipeeey@gmail.com
praiseubong28@gmail.com
sinenernest43@gmail.com
jaipeeey@gmail.com
imo.e.udoh@gmail.com
abdulkareemalameen75@gmail.com
yusufsaheed2012@gmail.com
salamsultan09@gmail.com
duzieblaise10@gmail.com
uawortu@gmail.com
jolextom@gmail.com
ohachutheodore@gmail.com
olawaleonasanya5@gmail.com
ttggwll@gmail.com
desirefeyisola2@gmail.com
davidtemisanalika@gmail.com
zionoluadeyanju@gmail.com
Olakumaps@gmail.com
awamchimere@gmail.com
ayomideiriajen@gmail.com
a.rasheedalabi@gmail.com
davidbriggd478@gmail.com
diamondbelema78@gmail.com
evavic44@gmail.com
spiffjekeygreen@gmail.com
osamudiameojo@gmail.com
obanlasamuelolakunle@gmail.com
alexegbuchulamginika@gmail.com
ukosarahiniobong@gmail.com
ebiringai@gmail.com
daniellupo30@gmail.com
oloyedeibrahimsmile@gmail.com
ogochukwuchibundu02@gmail.com
tobid6422@gmail.com
michaeliloba.2709@gmail.com
chima4484@gmail.com
munachianya@gmail.com
ademolutip@gmail.com
shrez1811@gmail.com
negbe.2300241@stu.cu.edu.ng
mayowayusuf3004@gmail.com
yekinirasheed2002@gmail.com
durosarovic@gmail.com
johnajayi008@gmail.com
baqee20072007@gmail.com
francismbah008@gmail.com
divinechukwu831@gmail.com
samuel.adesanya1love@gmail.com
davidchukwuyem73@gmail.com
obireoviemenaisrael@gmail.com
dukeoghenefejiroduke@gmail.com
ayaogesamuel@gmail.com
egbalajoy@gmail.com
Ayokomi2108@gmail.com
johnsonoca@gmail.com
devordan@gmail.com
abdulhafizoluwaseun@gmail.com
akeemjr001@gmail.com
yabvil25@gmail.com
fakorodehenry@gmail.com
esabublessing7@gmail.com
opcode3@gmail.com
anthonytwan75official@gmail.com
anthonytwan75official@gmail.com
nkwor.jane.chinelo@gmail.com
dannyalexandri@gmail.com
wisemanumanah@gmail.com
danielhaniel711@gmail.com
oketolasamuel001@gmail.com
lakesolve@gmail.com
marvellousabidemi2@gmail.com
elhassanehussaine@gmail.com
bammytaiwo95@gmail.com
progxdev@gmail.com
beniwealth70@gmail.com
oyikihgoodnews27@gmail.com
iamadeshinaeniola@gmail.com
aladebaruwa@gmail.com
olumidemichelle@gmail.com
abisolaemmanuel961@gmail.com
xrime011@gmail.com
idrisabdul775@gmail.com
aabdulgafar243423@stu.ui.edu.ng
chuksinnocent1@gmail.com
agberoryina@gmail.com
iziogbaraymond72@gmail.com
yusoofjnr@gmail.com
imerapheal056@gmail.com
summydeveloper@gmail.com
adegbitemustapha73@gmail.com
akinwalearemu0@gmail.com
arindedavid91@gmail.com
xpektra7@gmail.com
oloyedeelijah23@gmail.com
richardayomide15@gmail.com
ibraheemabdulrahman305@gmail.com
brightifeanyi799@gmail.com
petersongu2000@gmail.com
brightifeanyi799@gmail.com
johnfemi704@gmail.com
michaelaim17@gmail.com
chukwukaokonkwo99@gmail.com
dorathygift0@gmail.com
olatiseoluwatobiloba@gmail.com
akereletaiwo255@gmail.com
adedejitheophilus2018@gmail.com
israelolatunle2015@gmail.com
oluwaseyipeter450@gmail.com
obiasoguemmanuel96@gmail.com
hello@samkiel.dev
Ikonstudios29@gmail.com
odusolasemilore@gmail.com
adeniranrahman7@gmail.com
emenikeprosperbeales@gmail.com
adesholaajibola93@gmail.com
officialkittisolomon@gmail.com
davidagort@gmail.com
paulben.ajene@gmail.com
adelakin
emekapraiseo@gmail.com
ominudaniel@gmail.com
chimeremezeachoihim@gmail.com
Sadebowale092@gmail.com
kingsleyelevate@gmail.com
timcodes117@gmail.com
davidariyo109@gmail.com
mercynonyelu16@gmail.com
oluseyiwmwm@gmail.com
fabowalemuhawwal@gmail.com
osoemmanuel1969@gmail.com
odamike32@gmail.com
michaelaworetan@gmail.com
wisetega007@gmail.com
creativedivine5@gmail.com
alfredvachila@gmail.com
dharmkisz@gmail.com
techbyfemi@gmail.com
techbymobolaji@gmail.com
workwithdsc@gmail.com
hi@devaquila.me
justcovenant@gmail.com
timileyinoyelekan11@gmail.com
thejamesnick@gmail.com
okongordian@gmail.com
josephajibodu@gmail.com
samuelayibatarri.t@gmail.com
davidnwachukwum@gmail.com
bissongthankgod@gmail.com
adeboladuf@gmail.com
akinsanyaadeyinka4166@gmail.com
andrewoluwatomiwo@gmail.com
michealbolu19@gmail.com
eniaiyejuni.raphaelolukayode@gmail.com
aderinmolaakinkunmi@gmail.com
ibrahimdurotimi1@gmail.com
timiiseyemi@gmail.com
iyioluwaolaboye2003@gmail.com
Fadekunayomioluwa@gmail.com
ifeanyireed@gmail.com
horlabodehyibrahim@gmail.com
obafemiogunmokun@gmail.com
idawari005@gmail.com
fibijustus@gmail.com
koleajeolayinka@gmail.com
oriolowomustapha@gmail.com
adeyemiadigun12@gmail.com
orji.delight.onyedikachi@gmail.com
adebayo.ganiyuayomide@gmail.com
marvellousakinyemi910@gmai.com
theophilusjacob@gmail.com
yabvil25@gmail.com
Josephjerome773@gmail.com
ibrahimsherifdeji@gmail.com
hammedabdulbasit023@gmail.com
dmabdulkareem@gmail.com
destinyfelix4@gmail.com
davidadeyemi011@gmail.com
oluwafemionadokun@gmail.com
adahgodwin224@gmail.com
olamideanifowose2004@gmail.com
alawodes57@gmail.com
salvagainchibu@gmail.com
oluwoleemmanuel@gmail.com
alkrumehcaleb@gmail.com
abolamide77@gmail.com
olorunfemiisrael2@gmail.com
danielgbesimowo7@gmail.com
abdulrasheedbrimah@gmail.com
ramonadedotun550@gmail.com
horlajideid@gmail.com
princeakinola05@gmail.com
chrisnwachukwu107@gmail.com
olaitanoladapo29@gmail.com
olalekanibrahim011@gmail.com
philisobank@gmail.com
kodiugos@gmail.com
sukanmiismeal@gmail.com
michaeldaralola123@gmail.com
ayomidepopoola78@gmail.com
oluwayemioyinlola2@gmail.com
Mtemi0690@gmail.com
oyerindemuyiwa@gmail.com
emmanuel@obenitsolutions.com
sultan@devcareer.io
favour@devcareer.io 
`;

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const rawEmailEntries =
  RAW_NOMBA_CERTIFICATE_ELIGIBLE_EMAILS.split(/\s+/).filter(Boolean);
const normalizedEmailEntries = rawEmailEntries.map((email) =>
  email.trim().toLowerCase()
);
const uniqueEmailEntries = [...new Set(normalizedEmailEntries)];

export const nombaCertificateQualifiedEmails = uniqueEmailEntries.filter(
  (email) => EMAIL_PATTERN.test(email)
);

export const nombaCertificateEmailSeedStats = {
  rawCount: rawEmailEntries.length,
  uniqueCount: uniqueEmailEntries.length,
  validCount: nombaCertificateQualifiedEmails.length,
  duplicateCount: rawEmailEntries.length - uniqueEmailEntries.length,
  invalidEntries: uniqueEmailEntries.filter(
    (email) => !EMAIL_PATTERN.test(email)
  ),
};
