export { default as Dpds } from './Dpds/Dpds';
export { default as Home } from './Home/Home';
export { default as LaptopForDevelopers } from './L4d/LaptopForDevelopers';
export { default as Root } from './Root/Root';
export { default as Support } from './Support/Support';
export { default as Talents } from './Talents/Talents';
export { default as AboutUs } from './AboutUs/AboutUs';
export { default as ContactUs } from './ContactUs/ContactUs';
export { default as DpdsRegistration } from './Dpds/DpdsRegistration';
