export const talents=[
  {
    "id": "1",
    "fullName": "Uyi Osayi james",
    "currentCompany": "Our Pass",
    "experience": "2 Years",
    "availability": "Full Time",
    "skill": "Frontend Engineering",
    "linkedIn": "https://www.linkedin.com/in/jamesuyi/",
    "portfolioUrl": "",
    "emailAddress": "talk2james.uj@gmail.com"
  },
  {
    "id": "2",
    "fullName": "Olaniran Ridwan Olatunbosun",
    "currentCompany": "Bitmama",
    "experience": "2 Years",
    "availability": "Full Time",
    "skill": "Frontend Engineering",
    "linkedIn": "https://www.linkedin.com/in/ridwan-olaniran/",
    "portfolioUrl": "",
    "emailAddress": "olaniranolatubosun@gmail.com"
  },
  {
    "id": "133",
    "fullName": "Chilaka Precious Amarachi",
    "currentCompany": "",
    "experience": "2 Years",
    "availability": "Full Time",
    "skill": "Frontend Engineering",
    "linkedIn": "https://www.linkedin.com/in/precious-chilaka/",
    "portfolioUrl": "",
    "emailAddress": "preshchilaka06@gmail.com"
  },

    {
      "id": "4",
      "fullName": "Hassan Yakub",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/yakubu-hassan/",
      "portfolioUrl": "",
      "emailAddress": "yakubuh56@gmail.com"
    },
    {
      "id": "5",
      "fullName": "Umoh Esther",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "umohesther08@gmail.com"
    },
    {
      "id": "6",
      "fullName": "Francis Xavier",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/francisabonyi/",
      "portfolioUrl": "",
      "emailAddress": "francisabonyi@gmail.com"
    },
    {
      "id": "7",
      "fullName": "Bint Muhd",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/bintmuhd/",
      "portfolioUrl": "",
      "emailAddress": "bintmuhd247@gmail.com"
    },
    {
      "id": "8",
      "fullName": "Blessing Agadagba",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Data Science",
      "linkedIn": "https://www.linkedin.com/in/blessing-agadagba-0bba64165/",
      "portfolioUrl": "",
      "emailAddress": "agadagbablessing@gmail.com"
    },
    {
      "id": "9",
      "fullName": "Chimburuoma Gift Elenwo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/chimburuoma-gift-elenwo/",
      "portfolioUrl": "",
      "emailAddress": "elenwogift2@gmail.com"
    },
    {
      "id": "10",
      "fullName": "Appiah Collins",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "appiahc86@gmail.com"
    },
    {
      "id": "11",
      "fullName": "Yussif Issah",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "djiceman.gh@gmail.com"
    },
    {
      "id": "12",
      "fullName": "Dada Deborah Shalom",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "https://www.linkedin.com/in/deborah-dada-9aaa11134/",
      "portfolioUrl": "",
      "emailAddress": "shalomayokunnu@gmail.com"
    },
    {
      "id": "13",
      "fullName": "Olusola Glory",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "SWE",
      "linkedIn": "https://www.linkedin.com/in/glory-olusola/",
      "portfolioUrl": "",
      "emailAddress": "olusolagloryolamide@gmail.com"
    },
    {
      "id": "14",
      "fullName": "Raphael Limbikani Mbewe",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "rmbewe68@gmail.com"
    },
    {
      "id": "15",
      "fullName": "Bernard Arhia",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Full Stack",
      "linkedIn": "https://www.linkedin.com/in/bernard-arhia-ba4662104/",
      "portfolioUrl": "",
      "emailAddress": "bernardarhia@gmail.com"
    },
    {
      "id": "16",
      "fullName": "Onifade Dolapo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "hardolipey@gmail.com"
    },
    {
      "id": "17",
      "fullName": "Olajide Joshua",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/joshtom/",
      "portfolioUrl": "",
      "emailAddress": "olajidejoshua4real@gmail.com"
    },
    {
      "id": "18",
      "fullName": "Blossom Babalola",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/blossom-babalola/",
      "portfolioUrl": "",
      "emailAddress": "saphashb@gmail.com"
    },
    {
      "id": "19",
      "fullName": "Ayodeji Oladimeji",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/layobright/",
      "portfolioUrl": "",
      "emailAddress": "alayosingers@gmail.com"
    },
    {
      "id": "20",
      "fullName": "Ali Zaidan",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "zaidanali028@gmail.com"
    },
    {
      "id": "21",
      "fullName": "Steven Kolawole",
      "currentCompany": "",
      "experience": "4 Years",
      "availability": "Full Time",
      "skill": "Data Science",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "kolawolesteven99@gmail.com"
    },
    {
      "id": "22",
      "fullName": "Akinyemi Oluwafemi Tosin",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/femi-akinyemi/",
      "portfolioUrl": "",
      "emailAddress": "akinfemi46@gmail.com"
    },
    {
      "id": "23",
      "fullName": "Jeremiah Solomon",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "jeremiahsolomonfrancis@gmail.com"
    },
    {
      "id": "24",
      "fullName": "Khadijah Amusat",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Blockchain Dev",
      "linkedIn": "https://www.linkedin.com/in/khadijah-amusat/",
      "portfolioUrl": "",
      "emailAddress": "wuraola81@gmail.com"
    },
    {
      "id": "25",
      "fullName": "Ojonugwa Justice Alikali",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/ojonugwaalikali/",
      "portfolioUrl": "",
      "emailAddress": "alikali.ojonugwajustice@gmail.com"
    },
    {
      "id": "26",
      "fullName": "Bislon Zulu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Full Stack Engineering",
      "linkedIn": "https://www.linkedin.com/in/bislonzulu/",
      "portfolioUrl": "",
      "emailAddress": "bislonzulu1@outlook.com"
    },
    {
      "id": "27",
      "fullName": "Oyindamola Abiola",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Blockchain Dev",
      "linkedIn": "https://www.linkedin.com/in/oyindamolaabiola/",
      "portfolioUrl": "",
      "emailAddress": "mdcodes2308@gmail.com"
    },
    {
      "id": "28",
      "fullName": "Rexford Asamoah Agyapong",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Mobile Engineer",
      "linkedIn": "https://www.linkedin.com/in/rexfordasamoah/",
      "portfolioUrl": "",
      "emailAddress": "rexfordasamoah51@gmail.com"
    },
    {
      "id": "29",
      "fullName": "Chukwu Chukwuemeka",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Mobile Engineer",
      "linkedIn": "https://www.linkedin.com/in/chukwuemeka-chukwu-817020153/",
      "portfolioUrl": "",
      "emailAddress": "chukwuemekapascal123@gmail.com"
    },
    {
      "id": "30",
      "fullName": "Mutembo Phiri",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "thebabokaizen@gmail.com"
    },
    {
      "id": "31",
      "fullName": "Mercy Oyeniran",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "oyenimercy@gmail.com"
    },
    {
      "id": "32",
      "fullName": "Gbolahan Balogun",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/gbolahan-balogun-71357b1b9/",
      "portfolioUrl": "",
      "emailAddress": "gbolahanbalogun5@gmail.com"
    },
    {
      "id": "33",
      "fullName": "Amao Mutiat",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "https://www.linkedin.com/in/olaide-amao/",
      "portfolioUrl": "",
      "emailAddress": "mutiatamao@gmail.com"
    },
    {
      "id": "34",
      "fullName": "Saumu Nassoro Ali",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "saumunassir109@gmail.com"
    },
    {
      "id": "35",
      "fullName": "Agbakoba Donald",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "donaldagbakoba@gmail.com"
    },
    {
      "id": "36",
      "fullName": "Adaobi Ezenwa",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/adaobi-ezenwa-23926a19a/",
      "portfolioUrl": "",
      "emailAddress": "missdobis@gmail.com"
    },
    {
      "id": "37",
      "fullName": "Fiyin Akinsiku",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "fiyinakinsiku.b@gmail.com"
    },
    {
      "id": "38",
      "fullName": "Bernard Namangala",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "bernardnamangala@gmail.com"
    },
    {
      "id": "39",
      "fullName": "Hope Philip",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/hope-philip-29163014a/",
      "portfolioUrl": "",
      "emailAddress": "Idoreyenphilip@gmail.com"
    },
    {
      "id": "40",
      "fullName": "Godspower Uche",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/godspower-uche-5b61b4152/",
      "portfolioUrl": "",
      "emailAddress": "Godspowercuche56@gmail.com"
    },
    {
      "id": "41",
      "fullName": "Shermim Matunda Mwiwawi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/shermim-matunda/",
      "portfolioUrl": "",
      "emailAddress": "shermimmatunda@gmail.com"
    },
    {
      "id": "42",
      "fullName": "Amina Hassan",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "aminahass032@gmail.com"
    },
    {
      "id": "43",
      "fullName": "Daniel Otieno",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Quality Assurance",
      "linkedIn": "https://www.linkedin.com/in/danielotieno/",
      "portfolioUrl": "",
      "emailAddress": "danielotieno.ke@gmail.com"
    },
    {
      "id": "44",
      "fullName": "Sosanya Tumininu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/tumininu-sosanya/",
      "portfolioUrl": "",
      "emailAddress": "tumilizzy40@gmail.com"
    },
    {
      "id": "45",
      "fullName": "Lawal mukhtar",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/lawal-mukhtar/",
      "portfolioUrl": "",
      "emailAddress": "lmukhtar29@gmail.com"
    },
    {
      "id": "46",
      "fullName": "Desmond Edem",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/desmondedem/",
      "portfolioUrl": "",
      "emailAddress": "meetdesmond.edem@gmail.com"
    },
    {
      "id": "47",
      "fullName": "Owoseni Taiwo Hassanat",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Data Engineering",
      "linkedIn": "https://www.linkedin.com/in/thayehas/",
      "portfolioUrl": "",
      "emailAddress": "thayehas@gmail.com"
    },
    {
      "id": "48",
      "fullName": "Arafah Ayobami Ogunfemi",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/bami-ogunfemi/",
      "portfolioUrl": "",
      "emailAddress": "ayobamiarafat09@gmail.com"
    },
    {
      "id": "49",
      "fullName": "Ololade Oyedeji",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/zainab-oyedeji/",
      "portfolioUrl": "",
      "emailAddress": "ololadeoselu@yahoo.com"
    },
    {
      "id": "50",
      "fullName": "Olomitutu Olufemi Sunday",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/developermide/",
      "portfolioUrl": "",
      "emailAddress": "faginorish@gmail.com"
    },
    {
      "id": "51",
      "fullName": "Ropo John Olatujoye",
      "currentCompany": "",
      "experience": "5 Years",
      "availability": "Full Time",
      "skill": "Full Stack Engineering",
      "linkedIn": "https://www.linkedin.com/in/iamfiropo/",
      "portfolioUrl": "",
      "emailAddress": "iamfiropo@gmail.com"
    },
    {
      "id": "52",
      "fullName": "Balogun Azeezat Bukola",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "balogunzzt@gmail.com"
    },
    {
      "id": "53",
      "fullName": "Ayomikun Emmanuel",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/ayomikun-emmanuel/",
      "portfolioUrl": "",
      "emailAddress": "adeolaayo31@yahoo.com"
    },
    {
      "id": "54",
      "fullName": "Onayemi Hajarah",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/hajarah-onayemi/",
      "portfolioUrl": "",
      "emailAddress": ""
    },
    {
      "id": "55",
      "fullName": "Ajeigbe John Oluwaseyi",
      "currentCompany": "",
      "experience": "5 Years",
      "availability": "Full Time",
      "skill": "Full Stack Engineering",
      "linkedIn": "https://www.linkedin.com/in/ajeigbejohn/",
      "portfolioUrl": "",
      "emailAddress": "Slimmjohn4bright@gmail.com"
    },
    {
      "id": "56",
      "fullName": "Ajagbe Tunde Amodu",
      "currentCompany": "",
      "experience": "5 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/tundeajagbe/",
      "portfolioUrl": "",
      "emailAddress": "tundeajagbea@gmail.com"
    },
    {
      "id": "57",
      "fullName": "Temiloluwa Abiodun-Ojo",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/temiloluwa-abiodun-ojo/",
      "portfolioUrl": "",
      "emailAddress": "temiloluwaabiodunojo@gmail.com"
    },
    {
      "id": "58",
      "fullName": "Akinsoji hammed adisa",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Data Science",
      "linkedIn": "https://www.linkedin.com/in/adisa-akinsoji-53358a123/",
      "portfolioUrl": "",
      "emailAddress": "harksodje@gmail.com"
    },
    {
      "id": "59",
      "fullName": "Onothoja oghenemarho",
      "currentCompany": "",
      "experience": "4 Years",
      "availability": "Full Time",
      "skill": "Full Stack Engineering",
      "linkedIn": "https://www.linkedin.com/in/oghenemarho-onothoja-34082718b/",
      "portfolioUrl": "",
      "emailAddress": "marho219@gmail.com"
    },
    {
      "id": "60",
      "fullName": "OWOJORI ERNEST TOLULOPE",
      "currentCompany": "",
      "experience": "5 Years",
      "availability": "Full Time",
      "skill": "Data Science",
      "linkedIn": "https://www.linkedin.com/in/ernest-owojori/",
      "portfolioUrl": "",
      "emailAddress": "owojori.tolulope@gmail.com"
    },
    {
      "id": "61",
      "fullName": "Osunkunle Olanrewaju Olukunle",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/osunkunle-olanrewaju-841307129/",
      "portfolioUrl": "",
      "emailAddress": "osunkunleolanrewaju@gmail.com"
    },
    {
      "id": "62",
      "fullName": "Sijuade Ajagunna",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/sijuade-ajagunna-064458184/",
      "portfolioUrl": "",
      "emailAddress": "mahyor.sam@gmail.com"
    },
    {
      "id": "63",
      "fullName": "Olaoye Idris",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Full Stack Engineering",
      "linkedIn": "https://www.linkedin.com/in/idrisolaoye/",
      "portfolioUrl": "",
      "emailAddress": "idrisaboladeo@gmail.com"
    },
    {
      "id": "64",
      "fullName": "Samuel Nnaji",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/samuel-nnaji/",
      "portfolioUrl": "",
      "emailAddress": "samuelnnj@gmail.com"
    },
    {
      "id": "65",
      "fullName": "Okafor Ifeoma Sandra",
      "currentCompany": "",
      "experience": "3 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/ifeoma-sandra-okafor/",
      "portfolioUrl": "",
      "emailAddress": "sandraifeoma22@gmail.com"
    },
    {
      "id": "66",
      "fullName": "Abigail Olubanke  Eboda",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "olubanke.eboda@gmail.com"
    },
    {
      "id": "67",
      "fullName": "Azeez Adebisi",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Data Science",
      "linkedIn": "https://www.linkedin.com/in/samadebisi/",
      "portfolioUrl": "",
      "emailAddress": "samadebisi12@gmail.com"
    },
    {
      "id": "68",
      "fullName": "Blessing Olotewo",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "Olotewob@gmail.com"
    },
    {
      "id": "69",
      "fullName": "Tolulope David",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "tolulopedavid@gmail.com"
    },
    {
      "id": "70",
      "fullName": "Esther Umuhoza",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "https://www.linkedin.com/in/esther-umuhoza-b5579b208/",
      "portfolioUrl": "",
      "emailAddress": "eumuhoza83@gmail.com"
    },
    {
      "id": "71",
      "fullName": "Ajeigbe Olaoluwa Samuel",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "olaobey15@gmail.com"
    },
    {
      "id": "72",
      "fullName": "Okunola Opeyemi Peter",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "https://www.linkedin.com/in/opeyemi-peter-okunola/",
      "portfolioUrl": "",
      "emailAddress": "opeyemiadebowale1759@gmail.com"
    },
    {
      "id": "73",
      "fullName": "Miracle Anyanwu",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mac.mkboy1@gmail.com"
    },
    {
      "id": "74",
      "fullName": "Abdul Aziz Ali Alhassan",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "azizalialhassan@gmail.com"
    },
    {
      "id": "75",
      "fullName": "Amaechi Chimauche Daniel",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "chimaamaechi39@gmail.com"
    },
    {
      "id": "76",
      "fullName": "Okpara Blessing Oluchi",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "okparabon@gmail.com"
    },
    {
      "id": "77",
      "fullName": "Ben, Ekemini Sunday",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ekemiben.4@gmail.com"
    },
    {
      "id": "78",
      "fullName": "Judith Amegbe",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "judyseyram@gmail.com"
    },
    {
      "id": "79",
      "fullName": "Okafor Collins Izuchukwu",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "collinszurum@gmail.com"
    },
    {
      "id": "80",
      "fullName": "Mansur Ibrahim Nok",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mansuribrahimnok@gmail.com"
    },
    {
      "id": "81",
      "fullName": "Tijani Ayomide Lukman",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ayomidetijani6@gmail.com"
    },
    {
      "id": "82",
      "fullName": "Adenekan Abdulhazeem",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "omotayo4877@gmail.com"
    },
    {
      "id": "83",
      "fullName": "Nzeamalu Chikelue Austine",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "chikeluenzeamalu@gmail.com"
    },
    {
      "id": "84",
      "fullName": "Eke John Igwe",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ekejohnigwe@gmail.com"
    },
    {
      "id": "85",
      "fullName": "Kehinde Adedokun",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "kenney9224@gmail.com"
    },
    {
      "id": "86",
      "fullName": "GOODNESS UDOAKA",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "g.udoaka@gmail.com"
    },
    {
      "id": "87",
      "fullName": "Blesing Osas Obasohan",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "blessingstephaine2424@gmail.com"
    },
    {
      "id": "88",
      "fullName": "Bright Peter Bassey",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "brightbassey2001@gmail.com"
    },
    {
      "id": "89",
      "fullName": "Kanombola Kanombola",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "kanokanombola@gmail.com"
    },
    {
      "id": "90",
      "fullName": "Ajeigbe Kehinde Timothy",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ajeigbekehinde160@gmail.com"
    },
    {
      "id": "91",
      "fullName": "Jimmy MUTABAZI",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mutabazijimmy9@gmail.com"
    },
    {
      "id": "92",
      "fullName": "Tahir Adeleye",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "iruleadeleye@gmail.com"
    },
    {
      "id": "93",
      "fullName": "Miracle Nwadiaro",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "nwadiaromiracle@yahoo.com"
    },
    {
      "id": "94",
      "fullName": "Azeez Biliqis Temidayo",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Backend",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "biliqistemmy@gmail.com"
    },
    {
      "id": "95",
      "fullName": "OMOLEYE JULIUS",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "joshkid610@gmail.com"
    },
    {
      "id": "96",
      "fullName": "Kanyinsola Ibikunle",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ibikunlekanyinsola55@gmail.com"
    },
    {
      "id": "97",
      "fullName": "Amadi Emmanuel Ike",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "amadiike10@gmail.com"
    },
    {
      "id": "98",
      "fullName": "Frenny Chokka",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "vrennyc@gmail.com"
    },
    {
      "id": "99",
      "fullName": "Ezidi Miracle Chinedu",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mirablizz6@gmail.com"
    },
    {
      "id": "100",
      "fullName": "Ekaette Essien",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ekaetteessien27@gmail.com"
    },
    {
      "id": "101",
      "fullName": "Ajiboye Fatimo",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "fatimajiboy2000@gmail.com"
    },
    {
      "id": "102",
      "fullName": "Faith Ikhidero",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ikhidero.faithy@gmail.com"
    },
    {
      "id": "103",
      "fullName": "Sophie Temitope Shittu",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "sophieshittu61@gmail.com"
    },
    {
      "id": "104",
      "fullName": "Daniel Favour",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "favourd205@gmail.com"
    },
    {
      "id": "105",
      "fullName": "Afolabi Damilola Esther",
      "currentCompany": "",
      "experience": "",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "dafolabi71@gmail.com"
    },
    {
      "id": "106",
      "fullName": "SAFINA YAKUB",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "safiyyakareem2@gmail.com"
    },
    {
      "id": "107",
      "fullName": "Knollis Delle",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "knollisdelle@gmail.com"
    },
    {
      "id": "108",
      "fullName": "Richmond Asamoah Acquah",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Cloud Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "acquahrichmond.a@gmail.com"
    },
    {
      "id": "109",
      "fullName": "HAMZAT LATEEFAT OMOLARA",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "Hamzatlateefat.9@gmail.com"
    },
    {
      "id": "110",
      "fullName": "Amusan Peace Fehintoluwa",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "fehintoluwaamusan@gmail.com"
    },
    {
      "id": "111",
      "fullName": "Chinwendu Adaugo Nnamene",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "adaugonnamene@gmail.com"
    },
    {
      "id": "112",
      "fullName": "Miracle Amala Oluomachi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "oluomachiamala@yahoo.com"
    },
    {
      "id": "113",
      "fullName": "Aaliyah Aliyu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "aliyuaaliyah@gmail.com"
    },
    {
      "id": "114",
      "fullName": "Blessing Abosede Cliff",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mandyclive01@gmail.com"
    },
    {
      "id": "115",
      "fullName": "Oyibo Deborah oghenekevwe",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "Oyibodebbieo@gmail.com"
    },
    {
      "id": "116",
      "fullName": "Millicent Akosua Twumasi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Product Design",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "twummiley98@gmail.com"
    },
    {
      "id": "117",
      "fullName": "Rita Nwaodu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "rita.nwaodu@gmail.com"
    },
    {
      "id": "118",
      "fullName": "Grace Itiung",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "itiunggrace@gmail.com"
    },
    {
      "id": "119",
      "fullName": "Oyekale Alice Oluwatosin",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "hezealice@gmail.com"
    },
    {
      "id": "120",
      "fullName": "Adeshina Qoreebullahi Gaata",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "qoreebullahigaata@gmail.com"
    },
    {
      "id": "121",
      "fullName": "Ogunmola Emmanuel I.",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "emanuolumide@gmail.com"
    },
    {
      "id": "122",
      "fullName": "Josephine Adebayo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "josephinadebayo84@gmail.com"
    },
    {
      "id": "123",
      "fullName": "Toluwalope Victoria Adeti-Toyo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "victorioustolu@gmail.com"
    },
    {
      "id": "124",
      "fullName": "Hikmot Okunola",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "hikmotokunola@gmail.com"
    },
    {
      "id": "125",
      "fullName": "ALOSI JAMES MIRUKA",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "jamesmiruka955@gmail.com"
    },
    {
      "id": "126",
      "fullName": "Ayege Adewunmi Rukayat",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "adewunmiayege001@gmail.com"
    },
    {
      "id": "127",
      "fullName": "Jerry Aaron",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "https://www.linkedin.com/in/jerry-aaron-agbo/",
      "portfolioUrl": "",
      "emailAddress": "aaronjerry45@outlook.com"
    },
    {
      "id": "128",
      "fullName": "Ufuoma Bela Ogodo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/ufuoma-ogodo-399716109/",
      "portfolioUrl": "",
      "emailAddress": "ufuomaogodo@gmail.com"
    },
    {
      "id": "129",
      "fullName": "Ebulu Mercy Kelechi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "mercykeilechi@gmail.com"
    },
    {
      "id": "130",
      "fullName": "Opeyemi Akintunde",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "opeyemiakintunde10@gmail.com"
    },
    {
      "id": "131",
      "fullName": "Joy Asuquo Offiong",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "offiongjoyasuquo@gmail.com"
    },
    {
      "id": "132",
      "fullName": "Mbanugo Grace Chibunna",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "chiziterem01@gmail.com"
    },
    {
      "id": "133",
      "fullName": "Augusta Ehihebolo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Backend Engineering",
      "linkedIn": "https://www.linkedin.com/in/augusta-e",
      "portfolioUrl": "",
      "emailAddress": "ehiheboloaugustar@gmail.com"
    },
    {
      "id": "134",
      "fullName": "Tamara siansanda",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "tamarasiansanda18@gmail.com"
    },
    {
      "id": "135",
      "fullName": "Nezerwa Eligrand",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "eligrand2000@gmail.com"
    },
    {
      "id": "136",
      "fullName": "Joe Magolo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "magolojoe@duck.com"
    },
    {
      "id": "137",
      "fullName": "Afolabi Lateef Babatunde",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "afolabibabatunde247@gmail.com"
    },
    {
      "id": "138",
      "fullName": "Juliet Iboro Dickson",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "dicksonjuliett@gmail.com"
    },
    {
      "id": "139",
      "fullName": "Qaasim umar Olanrewaju",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "Omayr010@gmail.com"
    },
    {
      "id": "140",
      "fullName": "James Chukwuka Ohayi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "james.ohayi.243744@unn.edu.ng"
    },
    {
      "id": "141",
      "fullName": "Agboola Oluwatoyin",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "oluwatoyinagboola08@gmail.com"
    },
    {
      "id": "142",
      "fullName": "Destiny Aigbe",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "aigbedestinyic@gmail.com"
    },
    {
      "id": "143",
      "fullName": "Osamagioghomwenwi Oghagbon",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "oghomwenoghagbon@gmail.com"
    },
    {
      "id": "144",
      "fullName": "Grace Okon Effiong",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "graceffiong@gmail.com"
    },
    {
      "id": "145",
      "fullName": "Blessing Okonkwo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "theblessingokonkwo@gmail.com"
    },
    {
      "id": "146",
      "fullName": "Bridget Dayol",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "brioldav@gmail.com"
    },
    {
      "id": "147",
      "fullName": "kaputo jezreel",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "kaputojezreel@gmail.com"
    },
    {
      "id": "148",
      "fullName": "Emmanuella Neizer",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "emmanuellaneizer123@gmail.com"
    },
    {
      "id": "149",
      "fullName": "Treasure Ajefu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "treasureajefu@gmail.com"
    },
    {
      "id": "150",
      "fullName": "Ojochegbe Joy Alikali",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "joyalikali77@gmail.com"
    },
    {
      "id": "151",
      "fullName": "Tolulope Okunjoyo Deborah",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "toluokunjoyo@gmail.com"
    },
    {
      "id": "152",
      "fullName": "Daniel Ipogah",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "darnielipogah@gmail.com"
    },
    {
      "id": "153",
      "fullName": "Ifeoluwa Awoyemi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "ifeawoyemi@gmail.com"
    },
    {
      "id": "154",
      "fullName": "Oghenemeru Avwemoya",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "skiboss4life@gmail.com"
    },
    {
      "id": "155",
      "fullName": "Ezeh Shalom Ogechi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "shallygray@gmail.com"
    },
    {
      "id": "156",
      "fullName": "Chukwunonso Nwankwo",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "cnnonso@gmail.com"
    },
    {
      "id": "157",
      "fullName": "Gabriel Ozioma",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "gabrielheavenlydawn@gmail.com"
    },
    {
      "id": "158",
      "fullName": "Gladys Luke",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "lukegladys615@gmail.com"
    },
    {
      "id": "159",
      "fullName": "Somtochukwu Nwosu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "somynwosu@gmail.com"
    },
    {
      "id": "160",
      "fullName": "Abdulmuqsit Adam",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "muqsitadam@gmail.com"
    },
    {
      "id": "161",
      "fullName": "Adeleye Opeyemi Adebola",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "adebola786@gmail.com"
    },
    {
      "id": "162",
      "fullName": "Aisha Daodu",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "aishajumoke15@gmail.com"
    },
    {
      "id": "163",
      "fullName": "Jessica Joseph",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "jessicajoseph2019@yahoo.com"
    },
    {
      "id": "164",
      "fullName": "Duru Michael Chukwudi",
      "currentCompany": "",
      "experience": "2 Years",
      "availability": "Full Time",
      "skill": "Frontend Engineering",
      "linkedIn": "",
      "portfolioUrl": "",
      "emailAddress": "durumikaelc@gmail.com"
    }
  ]